config/routes.rb
Rails.application.routes.draw do

  get 'venues/start', to: 'venues#start'
  post 'venues/randomize', to: 'venues#randomize'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  resources :venues, only: [:show]
  resources :plans
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foursquare.rb
class Foursquare < ApplicationRecord

    # def self.search_venues(text)
    #     client.search_venues(:ll => '36.142064,-86.816086', :query => text)
    # end

    # def self.client
    #     @client ||= Foursquare2::Client.new(:client_id => 'ERRF2FFXVJG2FS3J3Q1V20VMQX1CAVCKVWIJ0YCQEBMNHOUG', :client_secret => 'LZK2WSFZAQARZC2ADXV2PCDDFL3Q2GBA1WHCJJBT5MNWTGQ3', :api_version => '20120609')
    # end

    def self.client
        @client ||= Foursquare2::Client.new(:client_id => '5DIN4YPJ52AAIMKKKMJ4VWOZHMQ3THYRLWICKM1UBPBFF1A3', :client_secret => 'Y1LO1QFMHEZMZRGX5QGKQVW4LLAHCTHKX2PYWXYYOCCNKRMK', :api_version => '20120609')
    end

    def self.find_venue(zipcode)
      zip_array = Venue.all.select { |venue| venue.zipcode == zipcode }
      zip_array.sample
    end

    def self.make_params(number)
      {name: Foursquare.client.venue(number)[:name],
      street_address: Foursquare.client.venue(number)[:location][:address],
      city:  Foursquare.client.venue(number)[:location][:city],
      state:  Foursquare.client.venue(number)[:location][:state],
      zipcode:  Foursquare.client.venue(number)[:location][:postalCode],
      category:  Foursquare.client.venue(number)[:categories][0][:name]}
    end

end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  belongs_to :venue

  validate :date_checker

  def date_checker
    if self.date < Date.today
      self.errors[:date] << "Date cannot be in the past"
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :plans
  has_many :venues, through: :plans

  has_secure_password

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true

end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :plans
  has_many :users, through: :plans

  validates :street_address, uniqueness: true

  def self.zipcodes
    self.all.map { |venue| venue.zipcode }.uniq
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in

  def current_user
    @user = User.find_by(id: session[:id])
  end

  def signed_in
    !!current_user
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def show
    find_plan
  end

  def new
    @plan = Plan.new(venue_id: params[:venue_id])
  end

  def create
    @plan = Plan.new(plan_params(:date, :venue_id))
    @plan.user_id = session[:id]
    if @plan.save
      redirect_to plan_path(@plan)
    else
      render :new
    end
  end

  def edit
    find_plan
  end

  def update
    find_plan
    if @plan.update(plan_params(:date))
      redirect_to plan_path(@plan)
    else
      render :edit
    end
  end

  def destroy
    find_plan
    @plan.destroy
    redirect_to user_path(current_user)
  end

  private

  def find_plan
    @plan = Plan.find_by(id: params[:id])
  end

  def plan_params(*args)
    params.require(:plan).permit(args)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:id] = @user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(@user)
    else
      # flash[:error] = "Your username/password do not match any records. Please try again."
      redirect_to login_path
    end
  end

  def logout
    # session[:id] = nil
    session.delete(:id)
    # flash[:success] = "Good Bye"
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    find_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    find_user
  end

  def update
    find_user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end


end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def start
  end

  def show
    @venue = Venue.find_by(id: params[:id])
  end

  def randomize
    zipcode = params.permit(:zipcode)[:zipcode].to_i
    @venue = Foursquare.find_venue(zipcode)
    if @venue
      redirect_to venue_path(@venue)
    else
      redirect_to venues_start_path, flash: {alert: "Could not find a location in that zip"}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>date with destiny</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/edit.html.erb
<%  if @plan.errors.any? %>
  <% @plan.errors.full_messages.each do |m| %>
  <%= m %><br>
  <% end %>
<% end %>

<%= form_for @plan do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.submit %>
<% end %>

<p> Your venue is: <%= @plan.venue.name %> </p>

<%= link_to 'delete plan', plan_path(@plan), method: 'delete' %>

app/views/plans/new.html.erb
<%  if @plan.errors.any? %>
  <% @plan.errors.full_messages.each do |m| %>
  <%= m %><br>
  <% end %>
<% end %>

<%= form_for @plan do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.hidden_field :venue_id, :value => @plan.venue_id %>
  <%= f.submit %>
<% end %>

<p> Your venue is: <%= @plan.venue.name %> </p>

app/views/plans/show.html.erb
<h1> Plan for <%= @plan.date %>, go to <%= @plan.venue.name %></h1>

<%= link_to 'edit plan', edit_plan_path(@plan) %>
<%= link_to 'delete plan', plan_path(@plan), method: 'delete' %>

app/views/plans/view.html.erb
<h1> Plan for <%= @plan.date %>, go to <%= @plan.venue.name %></h1>

app/views/users/_form.html.erb
<%  if @user.errors.any? %>
  <% @user.errors.full_messages.each do |m| %>
  <%= m %><br>
  <% end %>
<% end %>


<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if @user.plans.length > 0 %>
  <h2>Your plans</h2>
  <% @user.plans.each do |pl| %>
  <h1> Plan for <%= pl.date %>, go to <%= link_to pl.venue.name, plan_path(pl) %></h1>
  <% end %>
<% else %>
  <h2> You don't have any plans! </h2>
<% end %>

<h2><%= link_to 'make a date with destiny', venues_start_path %></h2>

<%= link_to 'edit user', edit_user_path(@user) %>

app/views/venues/show.html.erb
<h1><%= @venue.name %></h1>

<ul>
  <li><%= @venue.street_address %></li>
  <li><%= @venue.city %></li>
  <li><%= @venue.state %></li>
  <li><%= @venue.zipcode %></li>
  <li><%= @venue.category %></li>
</ul>

<%= form_tag new_plan_path, method: 'get' do %>
  <%= hidden_field_tag :venue_id, @venue.id %>
<%= submit_tag 'follow your destiny' %>
  <% end %>

<%= link_to 'defy your fate', venues_start_path %>

app/views/venues/start.html.erb
<% if flash[:alert] %>
  <div class="notice"><%= flash[:alert] %></div>
<% end %>

<%= form_tag '/venues/randomize', method: "post" do %>

  <%= label_tag 'zipcode' %>
  <%= number_field_tag 'zipcode' %>

  <%= submit_tag 'find your destined destination' %>

<% end %>